# Generated by Django 4.1.4 on 2022-12-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
