# Generated by Django 4.1.4 on 2022-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='imges',
            new_name='images',
        ),
    ]
